spring:
  security:
    oauth2:
      client:
        provider:
          client-app:
            # IMPORTANTE: Cambiamos 127.0.0.1 por el nombre del servicio en Docker
            authorization-uri: "http://auth-server:9000/oauth2/authorize"
            token-uri: "http://auth-server:9000/oauth2/token"
            user-info-uri: "http://auth-server:9000/userinfo"
            jwk-set-uri: "http://auth-server:9000/oauth2/jwks"
      resourceserver:
        jwt:
          issuer-uri: "http://auth-server:9000"